### ISSUE TITLE
Following tab empty

### ISSUE THREAD

**Issue by karlo2105** [azzy9/plugin.video.rumble#15]
I updated to the latest developing build 1.4.10 but following channels tab is still empty even after session reset. Any chance to fix ?
Thanks.

**Comment by azzy9** [comment]
Thank you for reporting this issue. I shall have a look when I have a chance.
I rarely use this plugin anymore and mainly use my lbry+ plugin so I will be a bit behind on discovering any issues.
Since this plugin relies on html scraping all it takes is a small change on their end for it to break the plugin

**Comment by karlo2105** [comment]
I use this plugin just to follow some channels which were kicked out of YT and went to Rumble only. It's not my alternative. It's good to have it as secondary alternative behind Odysee. Thanks for updating. 

May I ask you, when you have time, could you please take a look at [ottplayer](https://github.com/kodi-iptv-addons/kodi-iptv-addons) addon which is located in this repository. It is python 2 only and hasn't been updated since 2020.

**Comment by azzy9** [comment]
Sorry, I'm not looking to do any more projects.
This issue should be fixed in v1.4.11
