### ISSUE TITLE
No Livestream available on rt.com channel

### ISSUE THREAD

**Issue by SingleMalt2104** [azzy9/plugin.video.rumble#26]
@azzy9 

I have subscribed to the rt.com channel on https://rumble.com/c/RTNews, but I do not see the livestream within Kodi using your addon (v1.5.3). With my regular browser Brave I can view the livestream on rumble.com directly, which runs fine. But if I use Kodi (v20.2) it's simply not there to choose. As a German citizen, on YouTube rt.com, and probably other channels, are unavailabel for me, but on rumble.com this should be no problem. Or am I missing something, and this has something to do with Kodi directly, and me being a German internet user?

**Comment by azzy9** [comment]
It doesn't pick it up due to the REGEX needing to be changed to to search for live streams. As the plugin works by scraping, all it takes is one change to break it all and then require the REGEX to be changed to be fixed, it gets tedious after a while (especially for a plugin I do not use much anymore).
When I get time I can look to add it.

**Comment by SingleMalt2104** [comment]
Thanks for your statement on the matter. Please take all the time you need on this, no need to rush it, if the solution is as delicate as you say it is. A broken addon surely wants no one.

**Comment by ivoruetsche** [comment]
:-) Thanks a lot for your work :-)

Would be nice, to have live stream back

**Comment by azzy9** [comment]
Should be fixed in v1.6.0

**Comment by ivoruetsche** [comment]
Nice - thanks a lot
